uso_de_suelo_shp=read_sf("../inegiusodesuelo/inegiusodesuelo.shp")


clasificador_descripcion_a_friccion <- function(descripc) {
  friccion_map <- c(
    "DESPROVISTO DE VEGETACIÓN" = 0.1, # = ÁREA DESPROVISTA DE VEGETACIÓN
    "ASENTAMIENTOS HUMANOS" = 0.95,   # = URBANO CONSTRUIDO
    "CUERPO DE AGUA" = 0.0,           # = AGUA
    "SELVA BAJA CADUCIFOLIA" = 0.7,
    "BOSQUE DE OYAMEL" = 0.6,         # similar to other forests
    "BOSQUE CULTIVADO" = 0.35,
    "BOSQUE DE CEDRO" = 0.6,
    "BOSQUE MESÓFILO DE MONTAÑA" = 0.6,
    "BOSQUE DE PINO" = 0.6,
    "BOSQUE DE GALERÍA" = 0.42,
    "BOSQUE DE TÁSCATE" = 0.6,
    "BOSQUE DE PINO-ENCINO" = 0.75,
    "BOSQUE DE ENCINO" = 0.6,
    "SIN VEGETACIÓN APARENTE" = 0.1,
    "VEGETACION SECUNDARIA ARBUSTIVA DE BOSQUE DE OYAMEL" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE BOSQUE DE ENCINO" = 0.6,
    "AGRICULTURA DE TEMPORAL ANUAL" = 0.8,
    "PASTIZAL INDUCIDO" = 0.8,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE DE PINO" = 0.6,
    "BOSQUE DE ENCINO-PINO" = 0.75,
    "MATORRAL CRASICAULE" = 0.7,
    "AGRICULTURA DE HUMEDAD ANUAL" = 0.8, # assume same as riego anual
    "MATORRAL DESÉRTICO ROSETÓFILO" = 0.7,
    "PASTIZAL CULTIVADO" = 0.8,
    "PASTIZAL HALÓFILO" = 0.8,
    "AGRICULTURA DE RIEGO ANUAL" = 0.8,
    "AGRICULTURA DE RIEGO ANUAL Y PERMANENTE" = 0.8,
    "AGRICULTURA DE RIEGO ANUAL Y SEMIPERMANENTE" = 0.8,
    "AGRICULTURA DE RIEGO PERMANENTE" = 0.8,
    "AGRICULTURA DE RIEGO SEMIPERMANENTE" = 0.8,
    "AGRICULTURA DE RIEGO SEMIPERMANENTE Y PERMANENTE" = 0.8,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE DE OYAMEL" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE MATORRAL CRASICAULE" = 0.7,
    "AGRICULTURA DE TEMPORAL ANUAL Y PERMANENTE" = 0.8,
    "AGRICULTURA DE TEMPORAL PERMANENTE" = 0.8,
    "AGRICULTURA DE TEMPORAL SEMIPERMANENTE" = 0.8,
    "AGRICULTURA DE TEMPORAL ANUAL Y SEMIPERMANENTE" = 0.8,
    "AGRICULTURA DE TEMPORAL SEMIPERMANENTE Y PERMANENTE" = 0.8,
    "VEGETACIÓN HALÓFILA HIDRÓFILA" = 0.6,
    "PALMAR INDUCIDO" = 0.7,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE BOSQUE DE PINO" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE DE CEDRO" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE BOSQUE DE TÁSCATE" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE MESÓFILO DE MONTAÑA" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE DE TÁSCATE" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE BOSQUE MESÓFILO DE MONTAÑA" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE BOSQUE DE PINO-ENCINO" = 0.75,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE SELVA BAJA CADUCIFOLIA" = 0.7,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE DE PINO-ENCINO" = 0.75,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE DE ENCINO" = 0.6,
    "TULAR" = 0.6,
    "VEGETACIÓN SECUNDARIA ARBUSTIVA DE BOSQUE DE ENCINO-PINO" = 0.75,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE BOSQUE DE ENCINO-PINO" = 0.75,
    "VEGETACIÓN SECUNDARIA ARBÓREA DE SELVA BAJA CADUCIFOLIA" = 0.7,
    "VEGETACIÓN SECUNDARIA HERBÁCEA DE BOSQUE DE ENCINO" = 0.6,
    "VEGETACIÓN SECUNDARIA HERBÁCEA DE SELVA BAJA CADUCIFOLIA" = 0.7,
    "PRADERA DE ALTA MONTAÑA" = 0.6
  )
  
  return(friccion_map[descripc])
}
